export const heading={
    all:{
        title:'Anniversary All Gifts',rate:'4.8'
    },

    'best-sellers':{
        title:'Bestselling Anniversary Gifts'
    }

}

export const data={
    all:[
        {
            id: 1,
            image: [
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_1.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_2.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_3.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_4.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_5.webp",
            ],
            link: "/decorated-chocolate-truffle-cake-half-kg",
            title: "Decorated Chocolate Truffle Cake Half Kg",
            rate: "4.5",
            price: "575",
            review: "73 reviews",
            delivery: "Today",
          },

          {
            id: 3,
            image: [
              "/Images/birthday/fudge brownie/fudge-brownie-cake-half-kg_1.webp",
              "/Images/birthday/fudge brownie/fudge-brownie-cake-half-kg_2.webp",
              "/Images/birthday/fudge brownie/fudge-brownie-cake-half-kg_3.webp",
              "/Images/birthday/fudge brownie/fudge-brownie-cake-half-kg_4.webp",
              "/Images/birthday/fudge brownie/fudge-brownie-cake-half-kg_5.webp",
            ],
            link: "/fudge-brownie-cake-half-kg",
            title: "Fudge Brownie Cake Half Kg",
            rate: "4.5",
            price: "675",
            review: "273 reviews",
            delivery: "Today",
          },
          {
              image: [
                "/Images/anniversary/anniversary-cake/anniversary-special-chocolate-cake-half-kg_1.webp",
                "/Images/anniversary/anniversary-cake/anniversary-special-chocolate-cake-half-kg_2.webp",
                "/Images/anniversary/anniversary-cake/anniversary-special-chocolate-cake-half-kg_3.webp",
                "/Images/anniversary/anniversary-cake/anniversary-special-chocolate-cake-half-kg_4.webp",
                "/Images/anniversary/anniversary-cake/anniversary-special-chocolate-cake-half-kg_5.webp",    
              ],
              link: "/anniversary-special-chocolate-cake-half-kg",
              title: "Anniversary Special Chocolate Cake- Half Kg",
              rate: "4.9",
              price: "725",
              review: "28 reviews",
              delivery: "Today",
            },
          {
            id: 4,
            image: [
              "/Images/birthday/pastel carnations/love-for-pastel-carnations-bouquet_1.webp",
              "/Images/birthday/pastel carnations/love-for-pastel-carnations-bouquet_2.webp",
              "/Images/birthday/pastel carnations/love-for-pastel-carnations-bouquet_3.webp",
              "/Images/birthday/pastel carnations/love-for-pastel-carnations-bouquet_4.webp",
              "/Images/birthday/pastel carnations/love-for-pastel-carnations-bouquet_5.webp",
            ],
            link: "/love-for-pastel-carnations-bouquet",
            title: "Love For Pastel Carnations Bouquet",
            rate: "4.8",
            price: "949",
            review: "92 reviews",
            delivery: "Today",
          },
          {
              image: [
                "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_1.webp",
                "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_2.webp",
                "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_3.webp",
                "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_4.webp",
                "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_1.webp",  
              ],
              link: "/personalised-champange-couple-gift-box",
              title: "Personalised Champange Couple Gift Box",
              rate: "5.0",
              price: "1699",
              review: "1 reviews",
              delivery: "Tomorrow",
            },
            {
                image: [
                  "/Images/anniversary/memories-frame/heartfelt-memories-frame_1.webp",
                 "/Images/anniversary/memories-frame/heartfelt-memories-frame_2.webp",
                 "/Images/anniversary/memories-frame/heartfelt-memories-frame_1.webp",
                 "/Images/anniversary/memories-frame/heartfelt-memories-frame_2.webp",
                 "/Images/anniversary/memories-frame/heartfelt-memories-frame_1.webp", 
                ],
                link: "/heartfelt-memories-frame",
                title: "Heartfelt Memories Frame",
                price: "449",
                delivery: "Today",
              },
      
          {
            id:13,
            image: [
              "/Images/birthday/gerbera blossom/mixed-brilliance-gerbera-blossoms_1.webp",
              "/Images/birthday/gerbera blossom/mixed-brilliance-gerbera-blossoms_2.webp",
              "/Images/birthday/gerbera blossom/mixed-brilliance-gerbera-blossoms_3.webp",
              "/Images/birthday/gerbera blossom/mixed-brilliance-gerbera-blossoms_4.webp",
              "/Images/birthday/gerbera blossom/mixed-brilliance-gerbera-blossoms_5.webp",
            ],
            link: "/mixed-brilliance-gerbera-blossoms",
            title: "Special 8 Mixed Roses Bouquet",
            rate: "4.3",
            price: "549",
          }, 
          {
            image: [
              "/Images/anniversary/twin roses/twin-heart-arrangement_1.webp",
              "/Images/anniversary/twin roses/twin-heart-arrangement_2.webp",
              "/Images/anniversary/twin roses/twin-heart-arrangement_1.webp",
              "/Images/anniversary/twin roses/twin-heart-arrangement_2.webp",
              "/Images/anniversary/twin roses/twin-heart-arrangement_1.webp",
              
            ],
            link: "/twin-heart-arrangement",
            title: "Red Roses Connected Heart Arrangement",
            rate: "4.5",
            price: "2449",
            review: "80 reviews",
            delivery: "Today",
          },
    ],
    "best-sellers":[
        {
            id: 1,
            image: [
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_1.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_2.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_3.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_4.webp",
              "/Images/birthday/decorated truffle/decorated-chocolate-truffle-cake-half-kg_5.webp",
            ],
            link: "/decorated-chocolate-truffle-cake-half-kg",
            title: "Decorated Chocolate Truffle Cake Half Kg",
            rate: "4.5",
            price: "575",
            review: "73 reviews",
            delivery: "Today",
          },
          {
            image: [
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_1.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_2.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_4.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_5.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_6.webp",
            ],
            link: "/timeless-love-red-roses-bouquet-chocolate-cake",
            title: "Timeless Love Red Roses Bouquet & Chocolate Cake",
            rate: "4.7",
            price: "1449",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "360 reviews",
          },
          {
            image: [
              "/Images/anniversary/memories-frame/heartfelt-memories-frame_1.webp",
             "/Images/anniversary/memories-frame/heartfelt-memories-frame_2.webp",
             "/Images/anniversary/memories-frame/heartfelt-memories-frame_1.webp",
             "/Images/anniversary/memories-frame/heartfelt-memories-frame_2.webp",
             "/Images/anniversary/memories-frame/heartfelt-memories-frame_1.webp", 
            ],
            link: "/heartfelt-memories-frame",
            title: "Heartfelt Memories Frame",
            price: "449",
            delivery: "Today",
          },
          {
            image: [
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_1.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_2.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_4.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_5.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_8.webp",
            ],
            link: "/elegant-vibe-red-roses-bouquet-pineapple-cake",
            title: "Elegant Vibe Red Roses Bouquet & Pineapple Cake",
            rate: "4.9",
            price: "1449",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "86 reviews",
          },
          {
            image: [
              "/Images/birthday/fruit overload cake/fruit-overload-cake-half-kg_1.webp",
              "/Images/birthday/fruit overload cake/fruit-overload-cake-half-kg_2.webp",
              "/Images/birthday/fruit overload cake/fruit-overload-cake-half-kg_3.webp",
              "/Images/birthday/fruit overload cake/fruit-overload-cake-half-kg_4.webp",
              "/Images/birthday/fruit overload cake/fruit-overload-cake-half-kg_5.webp",
            ],
            link: "/fruit-overload-cake-half-kg",
            title: "Overload Fruit Cake Half Kg",
            rate: "5.0",
            price: "725",
            review: "273 reviews",
            delivery: "Today",
          },
          {
            image: [
              "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_1.webp",
              "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_2.webp",
              "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_3.webp",
              "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_4.webp",
              "/Images/anniversary/gift-box/personalised-champange-couple-gift-box_1.webp",  
            ],
            link: "/personalised-champange-couple-gift-box",
            title: "Personalised Champange Couple Gift Box",
            rate: "5.0",
            price: "1699",
            review: "1 reviews",
            delivery: "Tomorrow",
          },
          {
            image: [
              "/Images/birthday/red rose/vivid-love-6-red-roses-bouquet_1.webp",
              "/Images/birthday/red rose/vivid-love-6-red-roses-bouquet_2.webp",
              "/Images/birthday/red rose/vivid-love-6-red-roses-bouquet_3.webp",
              "/Images/birthday/red rose/vivid-love-6-red-roses-bouquet_4.webp",
              "/Images/birthday/red rose/vivid-love-6-red-roses-bouquet_1.webp",
            ],
            link: "/vivid-love-6-red-roses-bouquet",
            title: "Vivid Love 6 Red Roses Bouquet",
            rate: "5.0",
            price: "549",
            slug: "flowers",
            delivery: "Today",
          },
          {
            image: [
              "/Images/birthday/rocher/rocher-choco-bouquet_1.webp",
              "/Images/birthday/rocher/rocher-choco-bouquet_2.webp",
              "/Images/birthday/rocher/rocher-choco-bouquet_3.webp",
              "/Images/birthday/rocher/rocher-choco-bouquet_4.webp",
              "/Images/birthday/rocher/rocher-choco-bouquet_1.webp",
            ],
            link: "/rocher-choco-bouquet",
            title: "Rocher Choco Bouquet",
            rate: "4.8",
            price: "1899",
          },
    ]
}