export const heading={
    all:{title:'Combos : Gift Double Joy',rate:'4.5'},
    'best-sellers':{title:'Combos Bestsellers'}
}

export const data={
    all:[
        {
            image: [
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_1.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_2.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_3.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_4.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_8.webp",
            ],
            link: "/sweet-memories-pink-roses-bouquet-chocolate-cake",
            title: "Sweet Memories Pink Roses Bouquet & Chocolate Cake",
            rate: "5.0",
            price: "1499",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "767 reviews",
          },
          {
            image: [
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_1.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_2.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_3.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_4.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_8.webp",
            ],
            link: "/magical-dust-carnations-n-truffle-cake-combo",
            title: "Magical Dust Carnations & Truffle Cake Combo",
            rate: "4.9",
            price: "1799",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "302 reviews",
          },
          {
            image: [
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_1.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_2.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_4.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_5.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_6.webp",
            ],
            link: "/timeless-love-red-roses-bouquet-chocolate-cake",
            title: "Timeless Love Red Roses Bouquet & Chocolate Cake",
            rate: "4.7",
            price: "1449",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "360 reviews",
          },
          {
            image: [
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_1.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_2.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_4.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_5.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_8.webp",
            ],
            link: "/elegant-vibe-red-roses-bouquet-pineapple-cake",
            title: "Elegant Vibe Red Roses Bouquet & Pineapple Cake",
            rate: "4.9",
            price: "1449",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "86 reviews",
          },
          {
            image: [
              "/Images/together/dry-fruits-combo/dry-fruits-feast_1.webp",
              "/Images/together/dry-fruits-combo/dry-fruits-feast_2.webp",
              "/Images/together/dry-fruits-combo/dry-fruits-feast_3.webp",
              "/Images/together/dry-fruits-combo/dry-fruits-feast_4.webp",
              "/Images/together/dry-fruits-combo/dry-fruits-feast_1.webp",
              
            ],
            link: "/dry-fruits-feast",
            title: "Dry Fruits Feast",
            price: "2099",
            slug: "flowers-cakes",
            delivery: "Today",
          },
          {
            image: [
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_1.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_2.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_4.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_5.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_9.webp",
            ],
            link: "/brighten-up-the-day-roses-bouquet-pineapple-cake",
            title: "Brighten Up The Day Roses Bouquet & Pineapple Cake",
            rate: "5.0",
            price: "1540",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "76 reviews",
          },
          {
            image: [
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_1.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_2.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_3.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_4.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_5.webp",
            ],
            link: "/10-pink-roses-with-pineapple-cake-standard",
            title: "10 Pink Roses With Pineapple Cake Standard",
            rate: "4.8",
            price: "1149",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "13 reviews",
          },
          {
            image: [
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_1.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_2.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_3.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_4.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_5.webp",
              
            ],
            link: "/jasmine-whispers-n-chocolate-dreams",
            title: "Jasmine Whispers & Chocolate Dreams",
            rate: "5.0",
            price: "1249",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "133 reviews",
          },
    ],
    'best-sellers':[
        {
            image: [
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_1.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_2.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_3.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_4.webp",
              "/Images/birthday/pink-rose-and-cake/sweet-memories-pink-roses-bouquet-chocolate-cake_8.webp",
            ],
            link: "/sweet-memories-pink-roses-bouquet-chocolate-cake",
            title: "Sweet Memories Pink Roses Bouquet & Chocolate Cake",
            rate: "5.0",
            price: "1499",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "767 reviews",
          },
          {
            image: [
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_1.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_2.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_3.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_4.webp",
              "/Images/birthday/dust-carnations-truffle/magical-dust-carnations-n-truffle-cake-combo_8.webp",
            ],
            link: "/magical-dust-carnations-n-truffle-cake-combo",
            title: "Magical Dust Carnations & Truffle Cake Combo",
            rate: "4.9",
            price: "1799",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "302 reviews",
          },
          {
            image: [
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_1.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_2.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_4.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_5.webp",
              "/Images/birthday/timeless-love-cake/timeless-love-red-roses-bouquet-chocolate-cake_6.webp",
            ],
            link: "/timeless-love-red-roses-bouquet-chocolate-cake",
            title: "Timeless Love Red Roses Bouquet & Chocolate Cake",
            rate: "4.7",
            price: "1449",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "360 reviews",
          },
          {
            image: [
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_1.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_2.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_4.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_5.webp",
              "/Images/birthday/red-rose-pineapple/elegant-vibe-red-roses-bouquet-pineapple-cake_8.webp",
            ],
            link: "/elegant-vibe-red-roses-bouquet-pineapple-cake",
            title: "Elegant Vibe Red Roses Bouquet & Pineapple Cake",
            rate: "4.9",
            price: "1449",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "86 reviews",
          },
          {
            image: [
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_1.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_2.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_4.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_5.webp",
              "/Images/birthday/yellow-rose-pineapple/brighten-up-the-day-roses-bouquet-pineapple-cake_9.webp",
            ],
            link: "/brighten-up-the-day-roses-bouquet-pineapple-cake",
            title: "Brighten Up The Day Roses Bouquet & Pineapple Cake",
            rate: "5.0",
            price: "1540",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "76 reviews",
          },
          {
            image: [
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_1.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_2.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_3.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_4.webp",
              "/Images/birthday/pink-rose-cake/10-pink-roses-with-pineapple-cake-standard_5.webp",
            ],
            link: "/10-pink-roses-with-pineapple-cake-standard",
            title: "10 Pink Roses With Pineapple Cake Standard",
            rate: "4.8",
            price: "1149",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "13 reviews",
          },
          {
            image: [
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_1.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_2.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_3.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_4.webp",
              "/Images/together/candle-choco/jasmine-whispers-n-chocolate-dreams_5.webp",
              
            ],
            link: "/jasmine-whispers-n-chocolate-dreams",
            title: "Jasmine Whispers & Chocolate Dreams",
            rate: "5.0",
            price: "1249",
            slug: "flowers-cakes",
            delivery: "Today",
            review: "133 reviews",
          },
          {
            image: [
              "/Images/plants/good-vibes-plant-cake/good-vibes-plant-n-cake-combo_1.webp",
              "/Images/plants/good-vibes-plant-cake/good-vibes-plant-n-cake-combo_2.webp",
              "/Images/plants/good-vibes-plant-cake/good-vibes-plant-n-cake-combo_3.webp",
              "/Images/plants/good-vibes-plant-cake/good-vibes-plant-n-cake-combo_4.webp",
              "/Images/plants/good-vibes-plant-cake/good-vibes-plant-n-cake-combo_6.webp",
            ],
            link: "/good-vibes-plant-n-cake-combo",
            title: "Good Vibes Plant & Cake Combo",
            rate: "4.8",
            price: "1099",
            review: "28 reviews",
            delivery: "Today",
          },
          
    ]
}